// AUTO-GENERATED by scripts/generate_typescript_types.py — do not edit by hand.
// Regenerate with: python scripts/generate_typescript_types.py

export interface ChatRequest {
  message: string;
}

export interface ChatResponse {
  assistant_message: string;
  session_id: string;
  intent: string | null;
  awaiting_clarification: boolean;
}
