"""Generate frontend/src/types/generated.ts from the backend's Pydantic API schemas.

Run as `python scripts/generate_typescript_types.py` any time app/api/chat.py's
request/response models change, so the frontend's types can never silently
drift from the actual API contract (Module 00 build order step for Module 15's
typegen script, referenced by Module 17 section 9).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.api.chat import ChatRequest, ChatResponse  # noqa: E402

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "frontend" / "src" / "types" / "generated.ts"

_JSON_TYPE_TO_TS = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
}


def _resolve_type(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    if "$ref" in schema:
        ref_name = schema["$ref"].rsplit("/", 1)[-1]
        return _resolve_type(defs[ref_name], defs)
    if "anyOf" in schema:
        options = [_resolve_type(option, defs) for option in schema["anyOf"]]
        return " | ".join(dict.fromkeys(options))
    if schema.get("type") == "array":
        return f"{_resolve_type(schema['items'], defs)}[]"
    return _JSON_TYPE_TO_TS.get(schema.get("type", ""), "unknown" if schema.get("type") != "null" else "null")


def _emit_interface(name: str, model: type) -> str:
    schema = model.model_json_schema()
    defs = schema.get("$defs", {})
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for field_name, field_schema in schema.get("properties", {}).items():
        optional = "" if field_name in required else "?"
        ts_type = _resolve_type(field_schema, defs)
        lines.append(f"  {field_name}{optional}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    header = (
        "// AUTO-GENERATED by scripts/generate_typescript_types.py — do not edit by hand.\n"
        "// Regenerate with: python scripts/generate_typescript_types.py\n\n"
    )
    body = "\n\n".join(
        [
            _emit_interface("ChatRequest", ChatRequest),
            _emit_interface("ChatResponse", ChatResponse),
        ]
    )
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(header + body + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
